version: "3.9"

services:

  backend:
    build: ./backend

    ports:
      - "8001:8001"

    volumes:
      - ./backend:/app

    env_file:
      - .env

  frontend:
    build: ./frontend

    ports:
      - "8501:8501"

    volumes:
      - ./frontend:/app

    depends_on:
      - backend

    environment:
      BACKEND_URL: http://backend:8001